// generated by scripts/generate-vue-index.mjs
import DefaultLayout from './DefaultLayout/DefaultLayout.vue'
import PaginationComponent from './PaginationComponent/PaginationComponent.vue'
import calendarComponent from './calendarComponent/calendarComponent.vue'
import componentTemplate from './componentTemplate/componentTemplate.vue'
import coverComponent from './coverComponent/coverComponent.vue'
import listUseStarTemp from './listUseStarTemp/listUseStarTemp.vue'
import listComponent from './listComponent/listComponent.vue'
import loginComponent from './loginComponent/loginComponent.vue'
import menuComponent from './menuComponent/menuComponent.vue'
import modalComponent from './modalComponent/modalComponent.vue'
import mytestComponent from './mytestComponent/mytestComponent.vue'
import newComponent from './newComponent/newComponent.vue'
import paginationComponent from './pagination-module/paginationComponent.vue'
import ratingStarComponent from './ratingStarComponent/ratingStarComponent.vue'
import tableComponent from './tableComponent/tableComponent.vue'
import todoListComponent from './todoListComponent/todoListComponent.vue'

export {
  DefaultLayout,
  PaginationComponent,
  calendarComponent,
  componentTemplate,
  coverComponent,
  listUseStarTemp,
  listComponent,
  loginComponent,
  menuComponent,
  modalComponent,
  mytestComponent,
  newComponent,
  paginationComponent,
  ratingStarComponent,
  tableComponent,
  todoListComponent
}

export default {
  install(app) {
    app.component('DefaultLayout', DefaultLayout)
    app.component('PaginationComponent', PaginationComponent)
    app.component('calendarComponent', calendarComponent)
    app.component('componentTemplate', componentTemplate)
    app.component('coverComponent', coverComponent)
    app.component('listUseStarTemp', listUseStarTemp)
    app.component('listComponent', listComponent)
    app.component('loginComponent', loginComponent)
    app.component('menuComponent', menuComponent)
    app.component('modalComponent', modalComponent)
    app.component('mytestComponent', mytestComponent)
    app.component('newComponent', newComponent)
    app.component('paginationComponent', paginationComponent)
    app.component('ratingStarComponent', ratingStarComponent)
    app.component('tableComponent', tableComponent)
    app.component('todoListComponent', todoListComponent)
  }
}
